version: '3.4'
services:
  passgen-app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: password-check
    image: golang
    env_file: "./.env"
    ports:
      - ${API_PORT}:${API_PORT}
